### ISSUE TITLE
Win 平台克隆代码问题

### ISSUE THREAD

**Issue by iplanc** [KikiLetGo/MyPiano#5]
建议将目录中 `for :R %v IN (.:source:*.wav) do ( ffmpeg -i "mp3s` 文件移除或更名
Win平台在克隆的时候会报错：
```Cloning into 'D:\Project\Code\MyPaino'...
POST git-upload-pack (175 bytes)
Remote: Enumerating objects: 4, done.        
Remote: Counting objects:  25% (1/4)        
Remote: Counting objects:  50% (2/4)        
Remote: Counting objects:  75% (3/4)        
Remote: Counting objects: 100% (4/4)        
Remote: Counting objects: 100% (4/4), done.        
Remote: Compressing objects:  25% (1/4)        
Remote: Compressing objects:  50% (2/4)        
Remote: Compressing objects:  75% (3/4)        
Remote: Compressing objects: 100% (4/4)        
Remote: Compressing objects: 100% (4/4), done.        
Remote: Total 100 (delta 0), reused 1 (delta 0), pack-reused 96        
Error: invalid path 'for :R %v IN (.:source:*.wav) do ( ffmpeg -i "mp3s'
克隆远程存储库时遇到错误: Git failed with a fatal error.
unable to checkout working tree
Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'```

**Comment by alexanderhex** [comment]
J:\tmp\MyPiano-master\MyPiano-master>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

J:\tmp\MyPiano-master\MyPiano-master>wav2mp3.cmd
命令语法不正确。

J:\tmp\MyPiano-master\MyPiano-master>for /R ~na.mp3")

J:\tmp\MyPiano-master\MyPiano-master>python piano.py
Traceback (most recent call last):
  File "piano.py", line 4, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'J:\tmp\MyPiano-master\MyPiano-master>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

J:\tmp\MyPiano-master\MyPiano-master>wav2mp3.cmd
命令语法不正确。

J:\tmp\MyPiano-master\MyPiano-master>for /R ~na.mp3")

J:\tmp\MyPiano-master\MyPiano-master>python piano.py
Traceback (most recent call last):
  File "piano.py", line 4, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'J:\tmp\MyPiano-master\MyPiano-master>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

J:\tmp\MyPiano-master\MyPiano-master>wav2mp3.cmd
命令语法不正确。

J:\tmp\MyPiano-master\MyPiano-master>for /R ~na.mp3")

J:\tmp\MyPiano-master\MyPiano-master>python piano.py
Traceback (most recent call last):
  File "piano.py", line 4, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

**Comment by iplanc** [comment]
> J:\tmp\MyPiano-master\MyPiano-master>python main.py
> Traceback (most recent call last):
> File "main.py", line 1, in
> import pygame
> ModuleNotFoundError: No module named 'pygame'
> 
> J:\tmp\MyPiano-master\MyPiano-master>wav2mp3.cmd
> 命令语法不正确。
> 
> J:\tmp\MyPiano-master\MyPiano-master>for /R ~na.mp3")
> 
> J:\tmp\MyPiano-master\MyPiano-master>python piano.py
> Traceback (most recent call last):
> File "piano.py", line 4, in
> import pyaudio
> ModuleNotFoundError: No module named 'pyaudio'J:\tmp\MyPiano-master\MyPiano-master>python main.py
> Traceback (most recent call last):
> File "main.py", line 1, in
> import pygame
> ModuleNotFoundError: No module named 'pygame'
> 
> J:\tmp\MyPiano-master\MyPiano-master>wav2mp3.cmd
> 命令语法不正确。
> 
> J:\tmp\MyPiano-master\MyPiano-master>for /R ~na.mp3")
> 
> J:\tmp\MyPiano-master\MyPiano-master>python piano.py
> Traceback (most recent call last):
> File "piano.py", line 4, in
> import pyaudio
> ModuleNotFoundError: No module named 'pyaudio'J:\tmp\MyPiano-master\MyPiano-master>python main.py
> Traceback (most recent call last):
> File "main.py", line 1, in
> import pygame
> ModuleNotFoundError: No module named 'pygame'
> 
> J:\tmp\MyPiano-master\MyPiano-master>wav2mp3.cmd
> 命令语法不正确。
> 
> J:\tmp\MyPiano-master\MyPiano-master>for /R ~na.mp3")
> 
> J:\tmp\MyPiano-master\MyPiano-master>python piano.py
> Traceback (most recent call last):
> File "piano.py", line 4, in
> import pyaudio
> ModuleNotFoundError: No module named 'pyaudio'

尝试运行
```
pip install pygame
pip install pyaudio
```
安装所需的库
